name: Build Go Executable

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5"

      - name: Build executable
        run: |
          go build -o todo.exe ./

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: todo-exe
          path: todo.exe
